service: graphql-kungfu-example

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  memorySize: 256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"

functions:
  graphql:
    handler: dist/handler.server
    name: graphql-kungfu-api
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: dist/handler.playground
    name: graphql-kungfu-playground
    events:
      - http:
          path: playground
          method: get

plugins:
  - serverless-offline
